### ISSUE TITLE
Is there a way for get the z-domain transfer function according to kp-ki-kd-lamda-mu ?

### ISSUE THREAD

**Issue by tevfikyigit** [AlekseiTepljakov/fomcon-matlab#15]
I have been optimize my system using discrete fractional PID controller, I find optimum PID and Lambda-Mu parameters. I need z-domain transfer function for the my experimental studies.  I use my own methods to obtain TF, but it's not same with your block.

**Comment by extall** [comment]
Can you elaborate on "not [the] same with your block"? You can always compare the implementations in the frequency domain.
Besides that, you can use the `fpid` tool to implement the controller via an approximation.

**Comment by tevfikyigit** [comment]
Thank you, I used fpid tool and it works, can I obtain tf with z^-1? to apply FPGA with z-1 blocks? Also is there a way for choose order of the generated TF.

**Comment by extall** [comment]
You can use some included FOMCON functionality such as https://github.com/extall/fomcon-matlab/tree/master/utilities/implement/digital

Anyway, it looks like this issue is related to documentation. As such, I am closing it. Feel free to reach out to me otherwise if you have any remaining questions.

Additionally, I think that the documentation for FOMCON should clearly be updated. I will create a separate issue for this once again.
