### ISSUE TITLE
fractional version problem 2

### ISSUE THREAD

**Issue by denniskao872** [AlekseiTepljakov/fomcon-matlab#8]
sorry for typing again
I used the fod_v2_R2012b.zip you give me install in matlab 2012a. when i set the lanbda from fractional PID controller. i got a message from UI . It shows an error said **"Error in 'untitled/ Fractional  PID controller':Intialization commands cannot be evaluted --> Error: File fotf.m Line:1 Column 10 A class definition must be in an "@"directory"**. What is the problem about this message.is it still the version problem about it?(when i use the library of the block it shows ??? on it). 
thank you for your patience.

**Comment by denniskao872** [comment]
![1](https://user-images.githubusercontent.com/83489740/117244899-75251e80-ae6c-11eb-99cc-78948708d45d.png)
![2](https://user-images.githubusercontent.com/83489740/117244905-76eee200-ae6c-11eb-99ed-e2e4dd5b9bbd.png)

The problem is as attached

**Comment by denniskao872** [comment]
Duplicate of #
![01](https://user-images.githubusercontent.com/83489740/117245372-58d5b180-ae6d-11eb-92da-43693ad8fe33.png)
![02](https://user-images.githubusercontent.com/83489740/117245375-5a06de80-ae6d-11eb-8373-5feea4481105.png)

The problem is as attached

**Comment by extall** [comment]
Is FOMCON toolbox itself properly installed and all of its functions found on MATLAB path?

**Comment by denniskao872** [comment]
I set path to the fomcon toolbox and save it. the fod_v2_R2012b you give me i put it into the **models** folder and save path together.

**Comment by extall** [comment]
About the latest screenshot: `str` is generated by the `fracpid` function. If `fracpid` cannot be found, initialization of the block will fail and you will see ??? displayed on the block instead of the controller.

Pertaining to the earlier issues, I have just tried opening the latest `fod_v2` in Matlab R2012b, and although there were a few warnings in the Matlab Command Line about missing parameters, it should still operate normally.
Hence, please follow completely the checklist:

1. Completely remove all references to FOMCON from MATLAB path, close MATLAB;
2. Download the master branch of FOMCON toolbox from GitHub and unpack it into a permanent location;
3. Run MATLAB, locate the extracted folder `fomcon-matlab-master` in MATLAB, right-click on that folder, choose Add to Path → Folders and Subfolders.
4. Go to Path settings and Save Path for future use.
5. Type `fomcon` in MATLAB command line. If a UI opens, then FOMCON is installed correctly. You can now type `fod_v2` in the command line and drag and drop blocks from there to your desired model. Don't forget to change solver to a stiff system solver such as **ode23tb** or similar unless discrete time simulation is intended.

**Comment by denniskao872** [comment]
Thanks for your reply . I found the problem about my path(the error  is the path where I set is not a 'English' path ). When I reset the path to all English name. It works. 

At the last I want to ask one more question about fomcon.
Is there any video can learn about how to identification the function . because I thought I have a wrong setting in 'fofid'.

**Thanks again for your reply**

**Comment by extall** [comment]
This is an important point to consider, I mean regarding the non-latin characters in the path.
About documentation, please consider the papers that we have published on the topic throughout the years. In any case, it is a documentation issue, so this one is closed finally.
Good point on the video, though. I will think about this.
